branches:
  only:
    - master

skip_branch_with_pr: true

clone_depth: 5

image: Visual Studio 2022

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

build:
  project: platform/Windows/eduke32.sln
  parallel: true
  verbosity: minimal
